# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/optellen.xdc

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_optellen_0_0/design_1_optellen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_optellen_0_0 || ORIG_REF_NAME==design_1_optellen_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_vio_0_0/design_1_vio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_vio_0_0 || ORIG_REF_NAME==design_1_vio_0_0} -quiet] -quiet

# XDC: c:/02_PXL/01_Digitale_Systemen/Labo/Oef_2/Oef_2.gen/sources_1/bd/design_1/design_1_ooc.xdc
